"""Updated GaragePart table

Revision ID: 4d4bae0d2a34
Revises: 
Create Date: 2026-04-09 13:25:03.977053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d4bae0d2a34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_model_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delivery_available', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('installation_available', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'car_models', ['car_model_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('services_available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services_available', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('installation_available')
        batch_op.drop_column('delivery_available')
        batch_op.drop_column('car_model_id')

    # ### end Alembic commands ###
