"""Added pickup_available to GaragePart and service_option to OrderItem

Revision ID: 6335c160b32b
Revises: 4d4bae0d2a34
Create Date: 2026-04-20 13:41:27.283535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6335c160b32b'
down_revision = '4d4bae0d2a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_available', sa.Boolean(), nullable=True))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_option', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('service_option')

    with op.batch_alter_table('garage_parts', schema=None) as batch_op:
        batch_op.drop_column('pickup_available')

    # ### end Alembic commands ###
